import React from 'react';
import { Link } from 'react-router-dom';
import FAQ from '../components/FAQ';

const Financing: React.FC = () => {
  const faqItems = [
    {
      id: 1,
      question: "Will an energy storage system allow me to go off grid?",
      answer: "Yes, an energy storage system can allow you to go off-grid, but only if it's paired with sufficient renewable generation and properly sized for your energy needs."
    },
    {
      id: 2,
      question: "How do home solar batteries work?",
      answer: "Home solar batteries store extra energy generated by your solar panels during the day. This stored power can be used at night, during outages, or when solar production is low."
    },
    {
      id: 3,
      question: "What brands of solar batteries are available?",
      answer: "Popular solar battery brands include Tesla Powerwall, Enphase, LG Chem, and Sonnen. Other notable options are BYD, Generac, Panasonic, and SolarEdge Energy Bank."
    },
    {
      id: 4,
      question: "How much can I save with solar?",
      answer: "You can save 50–90% on your electricity bills depending on your system size, usage, and location. Savings increase over time as utility rates rise and your solar system offsets more grid power."
    }
  ];

  return (
    <div>
      {/* Hero Section */}
      <section className="overflow-hidden bg-white py-32 h-100 bg-gradient-to-br from-blue-900 via-blue-800 to-indigo-900 relative">
        <div className="absolute inset-0 bg-[url('https://images.pexels.com/photos/8853468/pexels-photo-8853468.jpeg')] bg-cover bg-center opacity-30"></div>
        <div className="mx-auto w-full px-6 lg:px-8 relative py-4 sm:py-4 md:py-24 lg:py-48 z-10">
          <div className="text-center">
            <h1 className="text-balance text-4xl md:text-4xl lg:text-6xl xl:text-7xl font-normal tracking-tight text-white">
              Power Your Home<br />Today, Pay Over Time
            </h1>
            <div className="mt-10 gap-x-6">
              <Link
                to="#"
                className="bg-white hover:bg-gray-100 py-4 px-5 me-2 mb-2 text-sm font-semibold uppercase font-mono text-gray-900 transition"
              >
                Design my system
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="overflow-hidden py-24 sm:py-32">
        <div className="max-w-[1300px] mx-auto max-w-7xl px-6 lg:px-8">
          <div className="text-xs mx-auto mb-5 uppercase border border-solid w-max py-2 px-6 rounded-md text-orange-500 border-orange-500">
            <span className="inline-block w-2 h-2 bg-orange-500 rounded-full mr-2"></span>
            Instant online approval
          </div>
          <h2 className="mt-2 text-center max-w-xl mx-auto text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-normal tracking-tight text-pretty">
            How it works?
          </h2>
          <p className="mt-6 text-xl max-w-lg mx-auto text-center text-gray-800">
            Our streamlined financing process gets you approved and installed faster than ever.
          </p>

          <div className="mx-auto py-12 grid grid-cols-1 lg:grid-cols-2 gap-12">
            <div className="lg:max-w-4xl">
              <img
                src="https://images.pexels.com/photos/8853477/pexels-photo-8853477.jpeg"
                alt="How it works"
                className="rounded-2xl w-full object-cover"
              />
            </div>
            <div className="lg:max-w-5xl relative">
              <div className="relative">
                <div className="absolute left-[10px] top-0 w-[5px] bg-gray-200 z-0 h-full"></div>
                <dl className="relative mt-10 max-w-xl sm:max-w-full space-y-14 text-base/7 text-gray-400 lg:max-w-none pl-8">
                  {[
                    {
                      step: "Step 1",
                      title: "Apply Online",
                      description: "Complete your application directly on our website in minutes."
                    },
                    {
                      step: "Step 2",
                      title: "Instant Decision",
                      description: "Receive your approval decision in seconds, not days."
                    },
                    {
                      step: "Step 3",
                      title: "Sign Digitally",
                      description: "Complete all loan agreements online with secure e-signatures."
                    },
                    {
                      step: "Step 4",
                      title: "Start Saving",
                      description: "Begin generating clean energy with $0 down financing for all products."
                    }
                  ].map((item, index) => (
                    <div key={index} className="relative pl-16">
                      <dt className="relative font-normal text-2xl text-gray-900">
                        <div className="absolute -left-16 top-1 w-5 h-5 bg-orange-500 rounded-full"></div>
                        <span className="text-orange-500 text-sm uppercase block mb-3">{item.step}</span>
                        {item.title}
                      </dt>
                      <dd className="text-gray-900 mt-4">{item.description}</dd>
                    </div>
                  ))}
                </dl>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="overflow-hidden bg-white py-24 sm:py-48 bg-gradient-to-l from-blue-900 to-indigo-900 relative">
        <div className="absolute inset-0 bg-[url('https://images.pexels.com/photos/8853468/pexels-photo-8853468.jpeg')] bg-cover bg-center opacity-30"></div>
        <div className="mx-auto w-full px-6 lg:px-8 relative z-10">
          <div className="mx-auto grid max-w-2xl grid-cols-1 gap-x-8 gap-y-16 sm:gap-y-20 lg:mx-0 lg:max-w-none lg:grid-cols-2">
            <div className="lg:pt-4 lg:pr-8">
              <div className="lg:max-w-lg">
                <div className="text-xs mb-5 uppercase border border-solid w-max py-2 px-6 rounded-md text-white border-white backdrop-blur-sm bg-white/10">
                  <span className="inline-block w-2 h-2 bg-white rounded-full mr-2"></span>
                  Benefits
                </div>
                <h2 className="mt-2 text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-normal tracking-tight text-pretty text-white">
                  No-Hassle Financing Benefits
                </h2>
                <p className="mt-6 text-xl text-white">
                  Simple, secure, and designed to fit your budget without the traditional financing hassles.
                </p>
                <ul className="mt-6 text-xl text-white space-y-3">
                  <li className="flex items-center">
                    <span className="text-green-400 mr-3">✓</span>
                    Competitive rates and flexible terms
                  </li>
                  <li className="flex items-center">
                    <span className="text-green-400 mr-3">✓</span>
                    No lien placed on your property
                  </li>
                  <li className="flex items-center">
                    <span className="text-green-400 mr-3">✓</span>
                    100% online application process
                  </li>
                  <li className="flex items-center">
                    <span className="text-green-400 mr-3">✓</span>
                    Instant approval decisions
                  </li>
                  <li className="flex items-center">
                    <span className="text-green-400 mr-3">✓</span>
                    No hidden fees or surprises
                  </li>
                </ul>
                <div className="mt-10 gap-x-6">
                  <Link
                    to="#"
                    className="bg-white hover:bg-gray-100 py-4 px-5 me-2 mb-2 text-sm font-semibold uppercase font-mono text-gray-900 transition"
                  >
                    Design my system
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Partnership Section */}
      <section className="max-w-[1600px] mx-auto px-6 lg:px-8 py-16 grid grid-cols-1 md:grid-cols-2 gap-10 items-center">
        <div className="flex justify-center w-sm max-w-[600px]">
          <img
            src="https://images.pexels.com/photos/8853465/pexels-photo-8853465.jpeg"
            alt="Mobile app interface"
            className="rounded-xl w-full h-auto shadow-lg"
          />
        </div>
        <div>
          <div className="text-xs mb-5 uppercase border border-solid w-max py-2 px-6 rounded-md text-orange-500 border-orange-500">
            <span className="inline-block w-2 h-2 bg-orange-500 rounded-full mr-2"></span>
            Trusted solar financing partner
          </div>
          <h1 className="text-3xl md:text-4xl lg:text-5xl xl:text-6xl leading-tight mb-6">
            Powered by <br />Sunlight Financial
          </h1>
          <p className="text-gray-600 text-base md:text-lg leading-relaxed max-w-lg mb-9">
            We've partnered with Sunlight Financial to offer $0 down financing for all our products.
          </p>
          <div className="mt-9">
            <Link
              to="#"
              className="bg-orange-500 hover:bg-orange-600 py-4 px-5 me-2 mb-2 text-sm font-normal text-white uppercase font-mono transition"
            >
              Design my system
            </Link>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="bg-white py-20 px-4 md:px-8 lg:px-14">
        <div className="w-full mx-auto">
          <h2 className="text-black text-3xl md:text-4xl lg:text-5xl xl:text-6xl mb-10">
            Solar Financing FAQs
          </h2>
          <FAQ items={faqItems} />
          <div className="w-full mx-auto mt-10 pt-12">
            <p className="text-base font-medium text-gray-400 text-center">
              Have a different question?{' '}
              <Link to="/contact" className="text-black underline hover:text-orange-500 transition">
                Contact us
              </Link>
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Financing;